export const singupEntrantModel = {
  mail_user: "",
  name_user: "",
  password_user: "",
  password2_user: "",
  date_user: "",
  direction_user: "",
  tel_user: "",
  title: "",
  spanEmail: "",
  spanName: "",
  spanPassword: "",
  spanPassword2: "",
  spanDate: "",
  spanDirection: "",
  spanTel: "",
  spanTitle: "",
};